connection: &connection
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres

development:
  <<: *connection
  database: itasa-development

test: &test
  <<: *connection
  database: itasa-test

test: &production
  <<: *connection
  database: itasa-production